// ─── Config (mutable for WE properties) ─────────────────────────────────────
export const cfg = {
  trailLength: 600,
  spaceScale: 12,
  camRadius: 22,
  camHeight: 8,
  sphereSize: 1.0,
  lineOpacity: 0.25,
  colorSaturation: 0.9,
  colorHueShift: 0.0,
  colorMode: 'dynamic',
  colorMix: 0.35,
  accentColor: [0.20, 0.72, 1.0],
  fogDensity: 0.018,
  energySensitivity: 1.0,
  mappingMode: 'latent',
  xFeature: 'brightness',
  yFeature: 'presence',
  zFeature: 'texture',
  xEmphasis: 1.0,
  yEmphasis: 1.0,
  zEmphasis: 1.0,
  glowIntensity: 0.7,
  breathingAmount: 0.18,
  pulseAmount: 0.45,
  autoRotate: true,
  autoRotateSpeed: 0.3,
};

export const MAX_SPHERES = 1200; // max possible trail length
